# SSL/TLS Configuration Override for NetworkMapper
# Use with: docker-compose -f docker-compose.yml -f docker-compose.ssl.yml up -d

version: '3.8'

services:
  frontend:
    ports:
      - "443:443"    # HTTPS only - HTTP disabled for security
    volumes:
      # SSL Certificate files
      - ./ssl/certs/networkmapper.crt:/etc/ssl/certs/networkmapper.crt:ro
      - ./ssl/certs/networkmapper.key:/etc/ssl/private/networkmapper.key:ro
      # SSL-enabled nginx configuration
      - ./ssl-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      # Ensure HTTPS is used for API calls
      - REACT_APP_API_URL=${REACT_APP_API_URL:-https://localhost:8000}
    depends_on:
      - backend

  backend:
    environment:
      # Update CORS to allow HTTPS origins
      - CORS_ORIGINS=${CORS_ORIGINS:-https://localhost:3000,https://localhost}
      # SSL-aware backend configuration
      - SSL_ENABLED=true
      - FORCE_HTTPS=true