version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: networkMapper
      POSTGRES_USER: nmapuser
      POSTGRES_PASSWORD: nmappass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://nmapuser:nmappass@db:5432/networkMapper
      CORS_ORIGINS: http://localhost:3000
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge