version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: networkMapper
      POSTGRES_USER: nmapuser
      POSTGRES_PASSWORD: nmappass
    # Remove port exposure - only backend needs database access
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env.network
    environment:
      DATABASE_URL: postgresql://nmapuser:nmappass@db:5432/networkMapper
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000}
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - ./backend/tests:/app/tests
      - ./backend/pytest.ini:/app/pytest.ini
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.network
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:8000}
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge