version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: networkMapper
      POSTGRES_USER: nmapuser
      POSTGRES_PASSWORD: nmappass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://nmapuser:nmappass@db:5432/networkMapper
      CORS_ORIGINS: http://localhost:3000
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    networks:
      - app-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - app-network
    command: npm start

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge